language: c

before_script:
  - "sudo apt-get install gcc-msp430"
  - "msp430-gcc --version"
  - "sudo apt-get install doxygen"
  - "doxygen --version"

script:
  - scons board=telosb toolchain=mspgcc oos_openwsn
  - scons board=gina   toolchain=mspgcc oos_openwsn
  - scons board=python toolchain=gcc    oos_openwsn
