language: c

before_script:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6D1D8367A3421AFB
- sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
- sudo apt-get update
# Download and install SOMMNIUM msp430-gcc binaries (This is the newmspgcc)
- mkdir ./temp
- cd    ./temp
- wget  http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/4_02_00_00/exports/msp430-gcc-support-files-1.194.zip
- wget  http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/4_02_00_00/exports/msp430-gcc-5.3.0.224_linux64.tar.bz2
- unzip msp430-gcc-support-files*.zip &
- sudo  mkdir -p /opt/msp430-toolchain && sudo tar xvjf msp430-gcc*.tar.bz2 -C /opt/msp430-toolchain --strip-components=1
- sudo  find msp430-gcc-support-files/include/ -name '*.ld' | xargs -I{} mv {} /opt/msp430-toolchain/msp430-elf/lib/ldscripts
- sudo  find msp430-gcc-support-files/include/ -name '*' | xargs -I{} mv {} /opt/msp430-toolchain/msp430-elf/include
- sudo  rm -rf *	#clean Downloads.dir
- cd ..
- echo "export PATH=\$PATH:/opt/msp430-toolchain/bin" >> .bashrc
- source .bashrc
- sudo apt-get install gcc-arm-none-eabi
# Let's register compiler versions
- msp430-elf-gcc --version
- arm-none-eabi-gcc --version
- sudo apt-get install gcc-msp430
- msp430-gcc --version
- sudo apt-get install doxygen
- doxygen --version

script:
- mkdir -p ./build/doc/
- scons docs
- scons board=telosb                                  toolchain=mspgcc verbose=1 oos_macpong
- scons board=openmote-cc2538                         toolchain=armgcc verbose=1 oos_macpong
- scons board=wsn430v14                               toolchain=mspgcc verbose=1 oos_macpong
- scons board=wsn430v13b                              toolchain=mspgcc verbose=1 oos_macpong
- scons board=gina                                    toolchain=mspgcc verbose=1 oos_macpong
- scons board=z1                                      toolchain=mspgcc verbose=1 oos_macpong
- scons board=iot-lab_M3                              toolchain=armgcc verbose=1 oos_macpong
- scons board=iot-lab_A8-M3                           toolchain=armgcc verbose=1 oos_macpong
- scons board=telosb                                  toolchain=mspgcc verbose=1 oos_openwsn
- scons board=openmote-cc2538                         toolchain=armgcc verbose=1 oos_openwsn
- scons board=openmote-cc2538     kernel=freertos     toolchain=armgcc verbose=1 oos_openwsn
- scons board=openmote-cc2538     goldenImage=sniffer toolchain=armgcc verbose=1 oos_sniffer
- scons board=openmote-cc2538     goldenImage=root    toolchain=armgcc verbose=1 oos_openwsn
- scons board=wsn430v14                               toolchain=mspgcc verbose=1 oos_openwsn
- scons board=wsn430v13b                              toolchain=mspgcc verbose=1 oos_openwsn
- scons board=gina                                    toolchain=mspgcc verbose=1 oos_openwsn
- scons board=z1                                      toolchain=mspgcc verbose=1 oos_openwsn
- scons board=python                                  toolchain=gcc    verbose=1 oos_openwsn
- scons board=iot-lab_M3                              toolchain=armgcc verbose=1 oos_openwsn
- scons board=iot-lab_A8-M3                           toolchain=armgcc verbose=1 oos_openwsn
- scons board=samr21_xpro                             toolchain=armgcc verbose=1 oos_openwsn
